name: MCONE-BukkitCoreSystem
version: 5.0.2-SNAPHOT
authors: [Domink Lippl, Rufus Maiwald]
main: eu.mcone.coresystem.bukkit.CoreSystem

commands:
  bukkit:
    description: Shows some information about the plugin and the server
  profile:
    aliases: profil
    description: Opens the profile menu
  feed:
    description: Sets the food bar to 10
    permission: system.bukkit.feed
  gamemode:
    aliases: gm
    description: Changes your gamemode
    permission: system.bukkit.gamemode
  heal:
    description: Sets the heal bar to 10
    permission: system.bukkit.heal
  stats:
    description: Opens the stats menu
  fly:
    description: Changes fly mode
    permission: system.bukkit.fly
  tp:
    aliases: teleport
    description: Teleports you or another player
    permission: system.bukkit.tp
  tphere:
    description: Teleports another player to yourself
    permission: system.bukkit.tp.others
  tpall:
    description: Teleports all players to another player
    permission: system.bukkit.tp.all
  tppos:
    description: Teleports the player to a coordinate
    permission: system.bukkit.tp.pos
  vanish:
    description: Hides the player from tab and makes him invisible
    permission: system.bukkit.vanish
  holo:
    description: Manage holograms
    permission: system.bukkit.holo
  npc:
    descirption: Spawns an NPC
    permission: system.bukkit.npc
  build:
    description: Allows to bypass build restrictions
    permission: system.bukkit.build
  world:
    aliases: [worlds,w]
    description: Manage worlds
    permission: system.bukkit.world

permissions:
  system:
    description: Bypass all MCONE-System Permissions
    children:
      system.bukkit:
        description: Bypass all MCONE-BukkitCoreSystem Permissions
        children:
          system.bukkit.feed:
            description: Feed the player
          system.bukkit.gamemode:
            description: Set the player to a specific gamemode
          system.bukkit.heal:
            description: Heal the player
          system.bukkit.fly:
            description: Allows the player to fly
          system.bukkit.tp:
            description: Teleports the player to another player or a specific location
            children:
              system.bukkit.tp.others:
                desciption: Allows the player to teleport other players
              system.bukkit.tp.all:
                description: Allows the player to teleport all online players to a player
              system.bukkit.tp.pos:
                description: Allows the player to teleport to a specific postition
          system.bukkit.vanish:
            description: Vanishes the player for all other players
          system.bukkit.reload:
            description: Reload the CoreSystem
          system.bukkit.holo:
            description: Access the holograms
          system.bukkit.npc:
            description: Allows to set NonCharacterPlayers
          system.bukkit.sign:
            dexcription: Allows to create colored signs
          system.bukkit.build:
            description: Allows to bypass build restrictions
          system.bukkit.cooldown:
            description: Allows to bypass the CooldownSystem
          system.bukkit.world:
            description: Allows to manage the servers worlds
