name: MCONE-BukkitCoreSystem
version: 10.0.0-SNAPHOT
authors: [Domink Lippl, Rufus Maiwald]
softdepend: [MCONE-CloudPlugin]
main: eu.mcone.coresystem.bukkit.BukkitCoreSystem

commands:
  bukkit:
    description: Shows some information about the plugin and the server
  profile:
    aliases: profil
    description: Opens the profile menu
  feed:
    description: Sets the food bar to 10
    permission: system.bukkit.feed
  gamemode:
    aliases: gm
    description: Changes your gamemode
    permission: system.bukkit.gamemode
  heal:
    description: Sets the heal bar to 10
    permission: system.bukkit.heal
  stats:
    description: Opens the stats menu
  fly:
    description: Changes fly mode
    permission: system.bukkit.fly
  tp:
    aliases: teleport
    description: Teleports you or another eu.mcone.coresystem.api.core.player
    permission: system.bukkit.tp
  tphere:
    description: Teleports another eu.mcone.coresystem.api.core.player to yourself
    permission: system.bukkit.tp.others
  tpall:
    description: Teleports all players to another eu.mcone.coresystem.api.core.player
    permission: system.bukkit.tp.all
  tppos:
    description: Teleports the eu.mcone.coresystem.api.core.player to a coordinate
    permission: system.bukkit.tp.pos
  vanish:
    description: Hides the eu.mcone.coresystem.api.core.player from tab and makes him invisible
    permission: system.bukkit.vanish
  holo:
    description: Manage holograms
    permission: system.bukkit.holo
  npc:
    descirption: Spawns an NPC
    permission: system.bukkit.npc
  build:
    description: Allows to bypass build restrictions
    permission: system.bukkit.build
  spawn:
    description: Allows to teleport to several registered spawns
  world:
    aliases: [worlds,w]
    description: Manage worlds
    permission: system.bukkit.world
  speed:
    description: in- or decreases the walk or fly speed
    permission: system.bukkit.speed

permissions:
  system:
    description: Bypass all MCONE-System Permissions
    children:
      system.bukkit:
        description: Bypass all MCONE-BukkitCoreSystem Permissions
        children:
          system.bukkit.feed:
            description: Feed the eu.mcone.coresystem.api.core.player
          system.bukkit.gamemode:
            description: Set the eu.mcone.coresystem.api.core.player to a specific gamemode
          system.bukkit.heal:
            description: Heal the eu.mcone.coresystem.api.core.player
          system.bukkit.fly:
            description: Allows the eu.mcone.coresystem.api.core.player to fly
          system.bukkit.tp:
            description: Teleports the eu.mcone.coresystem.api.core.player to another eu.mcone.coresystem.api.core.player or a specific location
            children:
              system.bukkit.tp.others:
                desciption: Allows the eu.mcone.coresystem.api.core.player to teleport other players
              system.bukkit.tp.all:
                description: Allows the eu.mcone.coresystem.api.core.player to teleport all online players to a eu.mcone.coresystem.api.core.player
              system.bukkit.tp.pos:
                description: Allows the eu.mcone.coresystem.api.core.player to teleport to a specific postition
          system.bukkit.vanish:
            description: Vanishes the eu.mcone.coresystem.api.core.player for all other players
          system.bukkit.reload:
            description: Reload the CoreSystem
          system.bukkit.holo:
            description: Access the holograms
          system.bukkit.npc:
            description: Allows to set NonCharacterPlayers
          system.bukkit.sign:
            dexcription: Allows to create colored signs
          system.bukkit.build:
            description: Allows to bypass build restrictions
          system.bukkit.cooldown:
            description: Allows to bypass the CooldownSystem
          system.bukkit.world:
            description: Allows to manage the servers worlds
          system.bukkit.setspawn:
            description: Allows to manage the spawn points
          system.bukkit.speed:
            description: Allows to use the speed cmd
          system.bukkit.world:
            description: Basic Permission for /world info and /world list
            children:
              system.bukkit.world.setspawn:
                description: Allows to set the current worlds spawn
              system.bukkit.world.upload:
                description: Allows to upload a specific world
              system.bukkit.world.delete:
                description: Allows to delete a specific world
              system.bukkit.world.modify:
                description: Allows to modify several values of a specific world
              system.bukkit.world.import:
                description: Allows to import an existing world from server folder
              system.bukkit.world.create:
                description: Allows to create a new world with specific parameters
