name: MCONE-BukkitCoreSystem
version: 10.1.0-SNAPHOT
authors: [Domink Lippl, Rufus Maiwald]
softdepend: [MCONE-CloudPlugin]
main: eu.mcone.coresystem.bukkit.BukkitCoreSystem

permissions:
  system:
    description: Bypass all MCONE-System Permissions
    children:
      system.bukkit:
        description: Bypass all MCONE-BukkitCoreSystem Permissions
        children:
          system.bukkit.feed:
            description: Feed the eu.mcone.coresystem.api.core.player
          system.bukkit.gamemode:
            description: Set the eu.mcone.coresystem.api.core.player to a specific gamemode
          system.bukkit.heal:
            description: Heal the eu.mcone.coresystem.api.core.player
          system.bukkit.fly:
            description: Allows the eu.mcone.coresystem.api.core.player to fly
          system.bukkit.tp:
            description: Teleports the eu.mcone.coresystem.api.core.player to another eu.mcone.coresystem.api.core.player or a specific location
            children:
              system.bukkit.tp.others:
                desciption: Allows the eu.mcone.coresystem.api.core.player to teleport other players
              system.bukkit.tp.all:
                description: Allows the eu.mcone.coresystem.api.core.player to teleport all online players to a eu.mcone.coresystem.api.core.player
              system.bukkit.tp.pos:
                description: Allows the eu.mcone.coresystem.api.core.player to teleport to a specific postition
          system.bukkit.vanish:
            description: Vanishes the eu.mcone.coresystem.api.core.player for all other players
          system.bukkit.reload:
            description: Reload the CoreSystem
          system.bukkit.sign:
            dexcription: Allows to create colored signs
          system.bukkit.build:
            description: Allows to bypass build restrictions
          system.bukkit.cooldown:
            description: Allows to bypass the CooldownSystem
          system.bukkit.world:
            description: Allows to manage the servers worlds
          system.bukkit.setspawn:
            description: Allows to manage the spawn points
          system.bukkit.speed:
            description: Allows to use the speed cmd
          system.bukkit.world:
            description: Basic Permission for /world info and /world list
            children:
              system.bukkit.world.npc:
                description: Allows to set NonCharacterPlayers
              system.bukkit.world.holo:
                description: Access the holograms
              system.bukkit.world.location:
                description: Allows to manage all locations
              system.bukkit.world.setspawn:
                description: Allows to set the current worlds spawn
              system.bukkit.world.upload:
                description: Allows to upload a specific world
              system.bukkit.world.delete:
                description: Allows to delete a specific world
              system.bukkit.world.modify:
                description: Allows to modify several values of a specific world
              system.bukkit.world.import:
                description: Allows to import an existing world from server folder
              system.bukkit.world.create:
                description: Allows to create a new world with specific parameters
