name: MCONE-BukkitCoreSystem
version: ${project.version}
authors: [Domink Lippl, Rufus Maiwald]
softdepend: [MCONE-CloudPlugin]
main: eu.mcone.coresystem.bukkit.BukkitCoreSystem

permissions:
  system:
    description: Bypass all MCONE-System Permissions
    children:
      system.bukkit:
        description: Bypass all MCONE-BukkitCoreSystem Permissions
        children:
          system.bukkit.feed:
            description: Feed the player
          system.bukkit.gamemode:
            description: Set the player to a specific gamemode
          system.bukkit.heal:
            description: Heal the player
          system.bukkit.fly:
            description: Allows the player to fly
          system.bukkit.invsee:
            description: Basic Permission for /invsee
            children: 
              system.bukkit.invsee.other:
                description: Allows the player to see inventories from all players
              system.bukkit.invsee.modify.other:
                description: Allows the player to modify inventories from all players
          system.bukkit.ecsee:
            description: Basic Permission for /ecsee
            children:
              system.bukkit.ecsee.self:
                description: Allows the player to open his own enderchest
              system.bukkit.ecsee.other:
                description: Allows the player to open enderchests from all players
              system.bukkit.ecsee.modify.other:
                description: Allows the player to modify enderchests from all players
          system.bukkit.tp:
            description: Teleports the player to another player or a specific location
            children:
              system.bukkit.tp.others:
                desciption: Allows the player to teleport other players
              system.bukkit.tp.all:
                description: Allows the player to teleport all online players to a player
              system.bukkit.tp.pos:
                description: Allows the player to teleport to a specific postition
          system.bukkit.vanish:
            description: Vanishes the player for all other players
          system.bukkit.reload:
            description: Reload the CoreSystem
          system.bukkit.sign:
            description: Allows to create colored signs
          system.bukkit.build:
            description: Allows to bypass build restrictions
          system.bukkit.cooldown:
            description: Allows to bypass the CooldownSystem
          system.bukkit.setspawn:
            description: Allows to manage the spawn points
          system.bukkit.speed:
            description: Allows to use the speed cmd
          system.bukkit.world:
            description: Basic Permission for /world info and /world list
            children:
              system.bukkit.world.npc:
                description: Allows to set NonCharacterPlayers
              system.bukkit.world.holo:
                description: Access the holograms
              system.bukkit.world.location:
                description: Allows to manage all locations
              system.bukkit.world.setspawn:
                description: Allows to set the current worlds spawn
              system.bukkit.world.upload:
                description: Allows to upload a specific world
              system.bukkit.world.delete:
                description: Allows to delete a specific world
              system.bukkit.world.modify:
                description: Allows to modify several values of a specific world
              system.bukkit.world.import:
                description: Allows to import an existing world from server folder
              system.bukkit.world.create:
                description: Allows to create a new world with specific parameters
